//! The FourQ curve: GF(p^2) arithmetic, point operations, and the fixed-base
//! scalar multiply.
//!
//! **This is not Ed25519.** FourQ is a twisted Edwards curve over the
//! quadratic extension of GF(2^127 - 1). Every point operation therefore costs
//! roughly twice a prime-field one, and nothing here is compatible with
//! `curve25519-dalek`. That is the whole reason this lives in its own module
//! rather than being folded into the existing crypto: the shapes look similar
//! and the arithmetic is unrelated.
//!
//! Transcribed from `qubic-typescript`'s `fourq.ts` / `fq.ts`, which are a port
//! of Cloudflare CIRCL, which ports the C reference in `qubic-cli`. The gate
//! for the whole module is the set of golden vectors in `tests.rs`, generated by
//! running the official `@qubic.org/crypto` package.

use super::fp::Fp;

/// An element of GF(p^2), written `[real, imaginary]`.
#[derive(Clone, Copy, PartialEq, Eq, Debug, Default)]
pub struct Fq(pub Fp, pub Fp);

impl Fq {
    pub const ZERO: Fq = Fq(Fp::ZERO, Fp::ZERO);
    pub const ONE: Fq = Fq(Fp::ONE, Fp::ZERO);

    pub fn add(self, o: Fq) -> Fq {
        Fq(self.0.add(o.0), self.1.add(o.1))
    }

    pub fn sub(self, o: Fq) -> Fq {
        Fq(self.0.sub(o.0), self.1.sub(o.1))
    }

    pub fn neg(self) -> Fq {
        Fq(self.0.neg(), self.1.neg())
    }

    /// Karatsuba multiply: (a0 + a1*i)(b0 + b1*i) with i^2 = -1.
    pub fn mul(self, o: Fq) -> Fq {
        let t1 = self.0.mul(o.0);
        let t2 = self.1.mul(o.1);
        let t3 = self.0.add(self.1);
        let t4 = o.0.add(o.1);
        let mut t5 = t3.mul(t4);
        t5 = t5.sub(t1);
        t5 = t5.sub(t2);
        Fq(t1.sub(t2), t5)
    }

    pub fn square(self) -> Fq {
        let t1 = self.0.add(self.1);
        let t2 = self.0.sub(self.1);
        let t3 = self.0.add(self.0);
        Fq(t1.mul(t2), t3.mul(self.1))
    }

    /// Inverse in the extension field: conj(a) / (a0^2 + a1^2).
    pub fn invert(self) -> Fq {
        let t1 = self.0.square();
        let t2 = self.1.square();
        let inv_norm = t1.add(t2).invert();
        Fq(self.0.mul(inv_norm), self.1.mul(inv_norm).neg())
    }

    /// Sign test, mirroring `fqSgn`: the real part decides unless it is zero.
    pub fn sgn(self) -> i64 {
        let s0 = self.0.sgn();
        let s1 = self.1.sgn();
        let use_s0 = s0 * s0;
        s0 * use_s0 + s1 * (1 - use_s0)
    }

    pub fn cmov(self, b: Fq, flag: u64) -> Fq {
        Fq(self.0.cmov(b.0, flag), self.1.cmov(b.1, flag))
    }

    /// 32 little-endian bytes: real part first, then imaginary.
    pub fn to_bytes(self) -> [u8; 32] {
        let mut out = [0u8; 32];
        out[..16].copy_from_slice(&self.0.to_bytes());
        out[16..].copy_from_slice(&self.1.to_bytes());
        out
    }

    pub fn from_bytes(b: &[u8]) -> Option<Fq> {
        Some(Fq(Fp::from_bytes(&b[..16])?, Fp::from_bytes(&b[16..])?))
    }
}

/// Build an `Fp` from a 128-bit literal, for `const` contexts. Only valid when
/// `v < 2^127`, which every constant below satisfies.
const fn fp_const(v: u128) -> Fp {
    Fp(v as u64, (v >> 64) as u64)
}

/// The curve parameter d, as `[real, imaginary]`.
pub const PARAM_D: Fq = Fq(
    fp_const(0x0000_0000_0000_00e4_0000_0000_0000_0142),
    fp_const(0x5e47_2f84_6657_e0fc_b382_1488_f1fc_0c8d),
);

/// The standard generator.
pub const GENERATOR: PointR1 = PointR1 {
    x: Fq(
        fp_const(0x1a34_7223_7c2f_b305_2865_92ad_7b38_33aa),
        fp_const(0x1e1f_553f_2878_aa9c_9686_9fb3_60ac_77f6),
    ),
    y: Fq(
        fp_const(0x0e3f_ee9b_a120_785a_b924_a246_2bcb_b287),
        fp_const(0x6e1c_4af8_630e_0242_49a7_c344_844c_8b5c),
    ),
    z: Fq::ONE,
    ta: Fq(
        fp_const(0x1a34_7223_7c2f_b305_2865_92ad_7b38_33aa),
        fp_const(0x1e1f_553f_2878_aa9c_9686_9fb3_60ac_77f6),
    ),
    tb: Fq(
        fp_const(0x0e3f_ee9b_a120_785a_b924_a246_2bcb_b287),
        fp_const(0x6e1c_4af8_630e_0242_49a7_c344_844c_8b5c),
    ),
};

/// A point in extended coordinates, R1.
#[derive(Clone, Copy, Debug)]
pub struct PointR1 {
    pub x: Fq,
    pub y: Fq,
    pub z: Fq,
    pub ta: Fq,
    pub tb: Fq,
}

/// A point in the precomputed "R2" form used by `point_add`: the addends are
/// pre-combined so a mixed addition costs fewer field multiplies.
#[derive(Clone, Copy, Debug)]
pub struct PointR2 {
    pub add_yx: Fq,
    pub sub_yx: Fq,
    pub dt2: Fq,
    pub z2: Fq,
}

pub fn identity() -> PointR1 {
    PointR1 {
        x: Fq::ZERO,
        y: Fq::ONE,
        z: Fq::ONE,
        ta: Fq::ZERO,
        tb: Fq::ZERO,
    }
}

pub fn point_double(p: &PointR1) -> PointR1 {
    let a = p.x.square();
    let b = p.y.square();
    let c = p.z.square();
    let c2 = c.add(c);
    let d = a.add(b);
    let x_plus_y_sqr = p.x.add(p.y).square();
    let e = x_plus_y_sqr.sub(d);
    let f = b.sub(a);
    let g = c2.sub(f);
    PointR1 {
        x: e.mul(g),
        y: d.mul(f),
        z: f.mul(g),
        ta: d,
        tb: e,
    }
}

pub fn to_r2(p: &PointR1) -> PointR2 {
    let t = p.ta.mul(p.tb);
    let dt = t.mul(PARAM_D);
    PointR2 {
        add_yx: p.y.add(p.x),
        sub_yx: p.y.sub(p.x),
        z2: p.z.add(p.z),
        dt2: dt.add(dt),
    }
}

pub fn point_add(p: &PointR1, q: &PointR2) -> PointR1 {
    let cc = p.ta.mul(p.tb);
    let h = p.y.sub(p.x);
    let bb = p.y.add(p.x);
    let a = h.mul(q.sub_yx);
    let bv = bb.mul(q.add_yx);
    let e = bv.sub(a);
    let hh = bv.add(a);
    let dd = p.z.mul(q.z2);
    let c2 = cc.mul(q.dt2);
    let f = dd.sub(c2);
    let g = dd.add(c2);
    PointR1 {
        x: e.mul(f),
        y: g.mul(hh),
        z: f.mul(g),
        ta: e,
        tb: hh,
    }
}

/// Negate a point in R2 form when `flag` is 1.
///
/// This is the reference's `r2Cneg`, and it is *not* "negate every
/// coordinate". Negating a point means (x, y) -> (x, -y), which in this
/// representation shows up as swapping `addYX` and `subYX` -- because
/// (y - x, y + x) for (x, -y) is (y + x, y - x) -- and separately flipping the
/// sign of `dt2`. Negating the coordinates themselves, which is what a first
/// reading suggests, produces a point that eventually drives Z to zero and the
/// inversion in `to_affine` then aborts.
pub fn r2_neg(p: &PointR2, flag: u64) -> PointR2 {
    PointR2 {
        add_yx: p.add_yx.cmov(p.sub_yx, flag),
        sub_yx: p.sub_yx.cmov(p.add_yx, flag),
        dt2: p.dt2.cmov(p.dt2.neg(), flag),
        z2: p.z2,
    }
}

/// Convert to affine coordinates. This needs one field inversion, which is why
/// the reference recomputes it per point and why batching it is worth doing.
pub fn to_affine(p: &PointR1) -> (Fq, Fq) {
    let z_inv = p.z.invert();
    (p.x.mul(z_inv), p.y.mul(z_inv))
}

/// Compress a point to 32 bytes: `LE(Y)` with the sign of X in bit 7 of the
/// last byte.
pub fn point_marshal(p: &PointR1) -> [u8; 32] {
    let (_x, y) = to_affine(p);
    let mut out = y.to_bytes();
    let s = _x.sgn();
    // b = (1 - s) / 2, so 1 when x is non-negative and 0 when negative.
    let b = (((1 - s) >> 1) & 1) as u8;
    out[31] |= b << 7;
    out
}

/// The group order n, little-endian 64-bit limbs.
const ORDER: [u64; 4] = [
    0x2fb2_540e_c776_8ce7,
    0xdfbd_004d_fe0f_7999,
    0xf053_9782_9cbc_14e5,
    0x0029_cbc1_4e5e_0a72,
];

/// If the scalar is even, add the group order so it becomes odd, which is what
/// the signed radix-16 recoding below needs. The private key is a raw 32-byte
/// value with no clamping, so this reduction is the only one that happens.
fn cond_add_order_n(x: &mut [u64; 5]) {
    let mask = (x[0] & 1).wrapping_sub(1);
    let mut carry = 0u64;
    for i in 0..4 {
        let (s, c1) = x[i].overflowing_add(ORDER[i] & mask);
        let (s, c2) = s.overflowing_add(carry);
        x[i] = s;
        carry = (c1 as u64) + (c2 as u64);
    }
    x[4] = x[4].wrapping_add(carry);
}

/// `x = (x - y) / 16`, with `y` interpreted as a sign-extended 128-bit value.
///
/// The borrow has to be computed from the comparison, not from the flag of a
/// single wrapped subtraction. Composing `sign_ext + borrow` into one
/// `overflowing_sub` looks equivalent and is not: with `sign_ext` all ones and
/// an incoming borrow, the sum wraps to zero, the subtraction then reports "no
/// borrow", and every higher limb silently gains one. The result looked like a
/// plausible field element and made the recoded top digit fall outside the
/// odd-multiple table, so the ladder selected a zero point and `Z` collapsed to
/// zero. The divergence is invisible in any single operation and only shows up
/// as a wrong identity.
fn sub_div16(x: &mut [u64; 5], y: i64) {
    // Sign extension of y into the upper limbs: all ones when y is negative.
    let sign_ext: u128 = if y < 0 { (1u128 << 64) - 1 } else { 0 };
    let mut borrow: u128 = 0;
    let mut r = [0u64; 5];
    for (i, slot) in r.iter_mut().enumerate() {
        // Limb 0 takes the low 64 bits of y; the rest take the sign mask plus
        // the borrow from the limb below.
        let sub = if i == 0 {
            (y as u128) & 0xFFFF_FFFF_FFFF_FFFF
        } else {
            sign_ext + borrow
        };
        let (v, b) = (x[i] as u128).overflowing_sub(sub);
        *slot = v as u64;
        borrow = b as u128;
    }
    // Shift the 320-bit result right by four bits.
    x[0] = (r[0] >> 4) | (r[1] << 60);
    x[1] = (r[1] >> 4) | (r[2] << 60);
    x[2] = (r[2] >> 4) | (r[3] << 60);
    x[3] = (r[3] >> 4) | (r[4] << 60);
    x[4] = r[4] >> 4;
}

/// Recode a 32-byte little-endian scalar into 65 signed radix-16 digits, each in
/// [-16, 15]. This is what lets the ladder add a precomputed multiple instead
/// of a doubled point.
fn recode_scalar(k: &[u8; 32]) -> [i8; 65] {
    let mut m = [0u64; 5];
    for i in 0..4 {
        let mut limb = [0u8; 8];
        limb.copy_from_slice(&k[i * 8..i * 8 + 8]);
        m[i] = u64::from_le_bytes(limb);
    }
    cond_add_order_n(&mut m);

    let mut d = [0i8; 65];
    for i in 0..64 {
        // Take the low 5 bits as a digit centred on zero.
        d[i] = ((m[0] & 0x1f) as i64 - 16) as i8;
        sub_div16(&mut m, d[i] as i64);
    }
    d[64] = ((m[0] & 0xff) as u8) as i8;
    d
}

/// `1G, 3G, 5G, ... 15G`, the odd multiples the ladder adds into.
fn odd_multiples(q: &PointR1) -> [PointR2; 8] {
    let p2 = point_double(q);
    let pp2 = to_r2(&p2);
    let mut table = [to_r2(q); 8];
    let mut r = *q;
    for (i, slot) in table.iter_mut().enumerate().skip(1) {
        r = point_add(&r, &pp2);
        *slot = to_r2(&r);
        let _ = i;
    }
    table
}

/// Fixed-base scalar multiply: `scalar * GENERATOR`.
///
/// This is a Montgomery ladder with 65 iterations of four doublings and one
/// mixed addition, i.e. roughly 325 point operations. There is no precomputed
/// base table, unlike dalek's 64 additions, which is why the naive Qubic path
/// is several times slower per candidate than the Nano one.
pub fn scalar_base_mult(scalar: &[u8; 32]) -> PointR1 {
    let tab = odd_multiples(&GENERATOR);
    let d = recode_scalar(scalar);
    let mut p = identity();

    for i in (0..65).rev() {
        p = point_double(&point_double(&point_double(&point_double(&p))));

        let di = d[i];
        let mask = (di >> 7) as i64;
        let abs_di = ((di as i64 + mask) ^ mask) as u64;
        let inx = (abs_di - 1) >> 1;
        let sig = ((di >> 7) & 1) as u64;

        // Select table[(|d| - 1) / 2] by constant-time walk.
        let mut sel = PointR2 {
            add_yx: Fq::ZERO,
            sub_yx: Fq::ZERO,
            dt2: Fq::ZERO,
            z2: Fq::ZERO,
        };
        for j in 0..8u64 {
            let hit = (((inx ^ j) as i64 - 1) >> 63) & 1;
            let t = tab[j as usize];
            sel = PointR2 {
                add_yx: sel.add_yx.cmov(t.add_yx, hit as u64),
                sub_yx: sel.sub_yx.cmov(t.sub_yx, hit as u64),
                dt2: sel.dt2.cmov(t.dt2, hit as u64),
                z2: sel.z2.cmov(t.z2, hit as u64),
            };
        }
        sel = r2_neg(&sel, sig);
        p = point_add(&p, &sel);
    }
    p
}

#[cfg(test)]
mod tests {
    use super::*;

    fn hex(b: &[u8]) -> String {
        b.iter().map(|x| format!("{x:02x}")).collect()
    }

    #[test]
    fn fq_field_axioms() {
        let mut r: u64 = 0x9e37;
        let mut next = || {
            r ^= r << 13;
            r ^= r >> 7;
            r ^= r << 17;
            r
        };
        let mut fq = || {
            let lo = next();
            let hi = next();
            Fq::from_u128_pair(lo, hi)
        };
        for _ in 0..500 {
            let (a, b, c) = (fq(), fq(), fq());
            // distributive
            assert_eq!(a.add(b).mul(c), a.mul(c).add(b.mul(c)));
            // commutative and associative
            assert_eq!(a.mul(b), b.mul(a));
            assert_eq!(a.add(b).add(c), a.add(b.add(c)));
            // square is a special case of mul
            assert_eq!(a.square(), a.mul(a));
            if a != Fq::ZERO {
                assert_eq!(a.mul(a.invert()), Fq::ONE);
            }
            // subtract is additive inverse
            assert_eq!(a.sub(a), Fq::ZERO);
        }
    }

    impl Fq {
        /// Test helper: build a non-trivial Fq from two u64s per part.
        fn from_u128_pair(lo: u64, hi: u64) -> Fq {
            Fq(
                Fp::from_u128(((hi as u128) << 64) | lo as u128),
                Fp::from_u128((lo as u128 ^ 0x9e37_79b9_7f4a_7c15) % ((1u128 << 127) - 1)),
            )
        }
    }

    #[test]
    fn generator_marshals_deterministically() {
        let m1 = point_marshal(&GENERATOR);
        let m2 = point_marshal(&GENERATOR);
        assert_eq!(m1, m2);
        assert_eq!(m1.len(), 32);
    }

    #[test]
    fn identity_marshals_to_one_with_no_sign_bit() {
        // The identity is (X=0, Y=1). `sgn(0) = 0`, so the sign bit is
        // (1 - 0) >> 1 = 0 and the high bit of the last byte stays clear.
        let m = point_marshal(&identity());
        assert_eq!(
            hex(&m),
            "0100000000000000000000000000000000000000000000000000000000000000"
        );
    }

    #[test]
    fn doubling_the_identity_stays_the_identity() {
        let d = point_double(&identity());
        // Affine coordinates must be (0, 1) again.
        let (x, y) = to_affine(&d);
        assert_eq!(x, Fq::ZERO);
        assert_eq!(y, Fq::ONE);
    }

    #[test]
    fn scalar_mult_is_deterministic() {
        let k = [7u8; 32];
        let a = point_marshal(&scalar_base_mult(&k));
        let b = point_marshal(&scalar_base_mult(&k));
        assert_eq!(a, b);
    }

    #[test]
    fn scalar_mult_handles_all_ones_scalar() {
        // An all-ones scalar is a legal raw K12 output; the recoder must not
        // panic or produce a degenerate point.
        let k = [0xffu8; 32];
        let m = point_marshal(&scalar_base_mult(&k));
        assert_eq!(m.len(), 32);
    }
}
