"""Generate Fp multiplication test vectors for the Qubic FourQ field.

The Rust unit tests cannot compute their own expected products: two 127-bit
values multiply to 254 bits, which does not fit in a u128, so an in-test
`a.to_u128() * b.to_u128()` overflows. Python has arbitrary precision, so it
can act as an oracle instead of a restatement of the code under test.

Run from the repository root:
    python3 research/qubic/fp_vectors.py
It rewrites nano-keys/src/qubic/fp_vectors.rs in place.
"""

P = (1 << 127) - 1
MASK64 = (1 << 64) - 1


class Rng:
    """xorshift64, matching the Rng in fp.rs so the vectors hit the same inputs."""

    def __init__(self, seed):
        self.s = seed & MASK64

    def next(self):
        x = self.s
        x ^= (x << 13) & MASK64
        x &= MASK64
        x ^= x >> 7
        x ^= (x << 17) & MASK64
        x &= MASK64
        self.s = x
        return x

    def fp(self):
        return (((self.next() << 64) | self.next()) & P) % P


def limbs(v):
    return v & MASK64, v >> 64


def fmt(lo, hi):
    return f"Fp(0x{lo:016x}, 0x{hi:016x})"


def main():
    r = Rng(0xFEEDFACE)
    rows = []
    for _ in range(512):
        a, b = r.fp(), r.fp()
        rows.append((a, b, (a * b) % P))

    lines = [
        f"        ({fmt(*limbs(a))}, {fmt(*limbs(b))}, {fmt(*limbs(p))}),"
        for a, b, p in rows
    ]
    body = "\n".join(lines)
    text = f'''//! Fp test vectors generated by an independent Python implementation.
//!
//! Source: `research/qubic/fp_vectors.py`. The point of these is that the
//! `u128` product of two 127-bit values needs 254 bits and does **not** fit in
//! a `u128`, so the unit tests could not compute their own expectation -- an
//! earlier version of `fp.rs` overflowed silently in the test rather than in
//! the implementation. These vectors are computed by arbitrary-precision
//! Python, which is an oracle rather than a restatement of the code under test.
//!
//! Regenerate with: python3 research/qubic/fp_vectors.py

use super::fp::Fp;\n\n/// `(a, b, a*b mod p)` triples, 512 of them.\npub const MUL_VECTORS: &[(Fp, Fp, Fp)] = &[
{body}
];
'''
    with open("nano-keys/src/qubic/fp_vectors.rs", "w") as f:
        f.write(text)
    print(f"wrote 512 vectors to nano-keys/src/qubic/fp_vectors.rs")


if __name__ == "__main__":
    main()
